# Generated by Django 3.1.3 on 2023-06-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('league', models.IntegerField()),
                ('cup', models.IntegerField()),
                ('concacaf', models.IntegerField()),
                ('age', models.IntegerField()),
                ('stadium', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('country', models.TextField(blank=True)),
                ('nameleague', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
            ],
        ),
    ]
